name: Question
description: Ask a question about using or configuring the Sprite Fusion Pixel Snapper node.
title: "[Question]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Share details so we can help quickly.
  - type: input
    id: version
    attributes:
      label: ComfyUI-spritefusion-pixel-snapper version / commit
      description: Include the git commit hash or release tag for this repository.
      placeholder: e.g. v0.3.0 or 1a2b3c4
    validations:
      required: true
  - type: textarea
    id: question_details
    attributes:
      label: Details
      description: Include the full question, context, and what you've tried so far.
      placeholder: |
        - What are you trying to achieve?
        - What steps have you taken?
        - Any error messages or unexpected behavior?
    validations:
      required: true
  - type: input
    id: comfyui_version
    attributes:
      label: ComfyUI version / commit
      placeholder: e.g. v0.6.0 or a1b2c3d
  - type: input
    id: operating_system
    attributes:
      label: Operating system
      placeholder: e.g. macOS 14.6, Windows 11, Ubuntu 24.04
